/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = paymentprocessor.Client.OpenAPIDateConverter;

namespace paymentprocessor.Model
{
    /// <summary>
    /// PaymentprocessorPaymentMethod
    /// </summary>
    [DataContract(Name = "paymentprocessorPaymentMethod")]
    public partial class PaymentprocessorPaymentMethod : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public PaymentprocessorCurrency? Currency { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentprocessorPaymentMethod" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentprocessorPaymentMethod()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentprocessorPaymentMethod" /> class.
        /// </summary>
        /// <param name="code">code (required).</param>
        /// <param name="title">title (required).</param>
        /// <param name="label">label.</param>
        /// <param name="enabled">enabled.</param>
        /// <param name="amount">amount.</param>
        /// <param name="currency">currency.</param>
        /// <param name="additionalInfo">additionalInfo.</param>
        /// <param name="isUpfront">isUpfront.</param>
        /// <param name="description">description.</param>
        /// <param name="restrictions">restrictions.</param>
        public PaymentprocessorPaymentMethod(string code = default(string), PaymentprocessorLocalizedText title = default(PaymentprocessorLocalizedText), PaymentprocessorLocalizedText label = default(PaymentprocessorLocalizedText), bool enabled = default(bool), PaymentprocessorMoney amount = default(PaymentprocessorMoney), PaymentprocessorCurrency? currency = default(PaymentprocessorCurrency?), string additionalInfo = default(string), bool isUpfront = default(bool), PaymentprocessorLocalizedText description = default(PaymentprocessorLocalizedText), List<PaymentprocessorPaymentMethodRestriction> restrictions = default(List<PaymentprocessorPaymentMethodRestriction>))
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for PaymentprocessorPaymentMethod and cannot be null");
            }
            this.Code = code;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for PaymentprocessorPaymentMethod and cannot be null");
            }
            this.Title = title;
            this.Label = label;
            this.Enabled = enabled;
            this.Amount = amount;
            this.Currency = currency;
            this.AdditionalInfo = additionalInfo;
            this.IsUpfront = isUpfront;
            this.Description = description;
            this.Restrictions = restrictions;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public PaymentprocessorLocalizedText Title { get; set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [DataMember(Name = "label", EmitDefaultValue = false)]
        public PaymentprocessorLocalizedText Label { get; set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [DataMember(Name = "enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", EmitDefaultValue = false)]
        public PaymentprocessorMoney Amount { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalInfo
        /// </summary>
        [DataMember(Name = "additionalInfo", EmitDefaultValue = false)]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// Gets or Sets IsUpfront
        /// </summary>
        [DataMember(Name = "isUpfront", EmitDefaultValue = true)]
        public bool IsUpfront { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public PaymentprocessorLocalizedText Description { get; set; }

        /// <summary>
        /// Gets or Sets Restrictions
        /// </summary>
        [DataMember(Name = "restrictions", EmitDefaultValue = false)]
        public List<PaymentprocessorPaymentMethodRestriction> Restrictions { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentprocessorPaymentMethod {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  AdditionalInfo: ").Append(AdditionalInfo).Append("\n");
            sb.Append("  IsUpfront: ").Append(IsUpfront).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Restrictions: ").Append(Restrictions).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
