/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = paymentprocessor.Client.OpenAPIDateConverter;

namespace paymentprocessor.Model
{
    /// <summary>
    /// PaymentContextOrderInfo
    /// </summary>
    [DataContract(Name = "PaymentContextOrderInfo")]
    public partial class PaymentContextOrderInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentContextOrderInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentContextOrderInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentContextOrderInfo" /> class.
        /// </summary>
        /// <param name="number">number (required).</param>
        /// <param name="grn">grn (required).</param>
        /// <param name="items">items.</param>
        public PaymentContextOrderInfo(string number = default(string), string grn = default(string), List<PaymentprocessorItem> items = default(List<PaymentprocessorItem>))
        {
            // to ensure "number" is required (not null)
            if (number == null)
            {
                throw new ArgumentNullException("number is a required property for PaymentContextOrderInfo and cannot be null");
            }
            this.Number = number;
            // to ensure "grn" is required (not null)
            if (grn == null)
            {
                throw new ArgumentNullException("grn is a required property for PaymentContextOrderInfo and cannot be null");
            }
            this.Grn = grn;
            this.Items = items;
        }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [DataMember(Name = "number", IsRequired = true, EmitDefaultValue = true)]
        public string Number { get; set; }

        /// <summary>
        /// Gets or Sets Grn
        /// </summary>
        [DataMember(Name = "grn", IsRequired = true, EmitDefaultValue = true)]
        public string Grn { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", EmitDefaultValue = false)]
        public List<PaymentprocessorItem> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentContextOrderInfo {\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Grn: ").Append(Grn).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
