/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing AvailabilityContextCustomer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailabilityContextCustomerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvailabilityContextCustomer
        //private AvailabilityContextCustomer instance;

        public AvailabilityContextCustomerTests()
        {
            // TODO uncomment below to create an instance of AvailabilityContextCustomer
            //instance = new AvailabilityContextCustomer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvailabilityContextCustomer
        /// </summary>
        [Fact]
        public void AvailabilityContextCustomerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvailabilityContextCustomer
            //Assert.IsType<AvailabilityContextCustomer>(instance);
        }

        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Fact]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
