/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing ConditionAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConditionActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConditionAction
        //private ConditionAction instance;

        public ConditionActionTests()
        {
            // TODO uncomment below to create an instance of ConditionAction
            //instance = new ConditionAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConditionAction
        /// </summary>
        [Fact]
        public void ConditionActionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConditionAction
            //Assert.IsType<ConditionAction>(instance);
        }
    }
}
