/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorPerformPaymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorPerformPaymentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorPerformPaymentResponse
        //private PaymentprocessorPerformPaymentResponse instance;

        public PaymentprocessorPerformPaymentResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorPerformPaymentResponse
            //instance = new PaymentprocessorPerformPaymentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorPerformPaymentResponse
        /// </summary>
        [Fact]
        public void PaymentprocessorPerformPaymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorPerformPaymentResponse
            //Assert.IsType<PaymentprocessorPerformPaymentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'IsUpfront'
        /// </summary>
        [Fact]
        public void IsUpfrontTest()
        {
            // TODO unit test for the property 'IsUpfront'
        }
    }
}
