/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorGetAvailablePaymentMethodRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorGetAvailablePaymentMethodRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorGetAvailablePaymentMethodRequest
        //private PaymentprocessorGetAvailablePaymentMethodRequest instance;

        public PaymentprocessorGetAvailablePaymentMethodRequestTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorGetAvailablePaymentMethodRequest
            //instance = new PaymentprocessorGetAvailablePaymentMethodRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorGetAvailablePaymentMethodRequest
        /// </summary>
        [Fact]
        public void PaymentprocessorGetAvailablePaymentMethodRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorGetAvailablePaymentMethodRequest
            //Assert.IsType<PaymentprocessorGetAvailablePaymentMethodRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'AuthenticateMethod'
        /// </summary>
        [Fact]
        public void AuthenticateMethodTest()
        {
            // TODO unit test for the property 'AuthenticateMethod'
        }
    }
}
