/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorListPaymentMethodsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorListPaymentMethodsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorListPaymentMethodsRequest
        //private PaymentprocessorListPaymentMethodsRequest instance;

        public PaymentprocessorListPaymentMethodsRequestTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorListPaymentMethodsRequest
            //instance = new PaymentprocessorListPaymentMethodsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorListPaymentMethodsRequest
        /// </summary>
        [Fact]
        public void PaymentprocessorListPaymentMethodsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorListPaymentMethodsRequest
            //Assert.IsType<PaymentprocessorListPaymentMethodsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'AuthenticateMethods'
        /// </summary>
        [Fact]
        public void AuthenticateMethodsTest()
        {
            // TODO unit test for the property 'AuthenticateMethods'
        }
    }
}
