/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorCurrency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorCurrencyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorCurrency
        //private PaymentprocessorCurrency instance;

        public PaymentprocessorCurrencyTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorCurrency
            //instance = new PaymentprocessorCurrency();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorCurrency
        /// </summary>
        [Fact]
        public void PaymentprocessorCurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorCurrency
            //Assert.IsType<PaymentprocessorCurrency>(instance);
        }
    }
}
