/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorLocalizedText
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorLocalizedTextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorLocalizedText
        //private PaymentprocessorLocalizedText instance;

        public PaymentprocessorLocalizedTextTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorLocalizedText
            //instance = new PaymentprocessorLocalizedText();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorLocalizedText
        /// </summary>
        [Fact]
        public void PaymentprocessorLocalizedTextInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorLocalizedText
            //Assert.IsType<PaymentprocessorLocalizedText>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
