/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorGetPaymentMethodRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorGetPaymentMethodRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorGetPaymentMethodRequest
        //private PaymentprocessorGetPaymentMethodRequest instance;

        public PaymentprocessorGetPaymentMethodRequestTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorGetPaymentMethodRequest
            //instance = new PaymentprocessorGetPaymentMethodRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorGetPaymentMethodRequest
        /// </summary>
        [Fact]
        public void PaymentprocessorGetPaymentMethodRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorGetPaymentMethodRequest
            //Assert.IsType<PaymentprocessorGetPaymentMethodRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'AuthenticateMethod'
        /// </summary>
        [Fact]
        public void AuthenticateMethodTest()
        {
            // TODO unit test for the property 'AuthenticateMethod'
        }
    }
}
