/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorPaymentMethodRestrictionCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorPaymentMethodRestrictionConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorPaymentMethodRestrictionCondition
        //private PaymentprocessorPaymentMethodRestrictionCondition instance;

        public PaymentprocessorPaymentMethodRestrictionConditionTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorPaymentMethodRestrictionCondition
            //instance = new PaymentprocessorPaymentMethodRestrictionCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorPaymentMethodRestrictionCondition
        /// </summary>
        [Fact]
        public void PaymentprocessorPaymentMethodRestrictionConditionInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorPaymentMethodRestrictionCondition
            //Assert.IsType<PaymentprocessorPaymentMethodRestrictionCondition>(instance);
        }

        /// <summary>
        /// Test the property 'ContextPath'
        /// </summary>
        [Fact]
        public void ContextPathTest()
        {
            // TODO unit test for the property 'ContextPath'
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
