/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorMoney
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorMoneyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorMoney
        //private PaymentprocessorMoney instance;

        public PaymentprocessorMoneyTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorMoney
            //instance = new PaymentprocessorMoney();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorMoney
        /// </summary>
        [Fact]
        public void PaymentprocessorMoneyInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorMoney
            //Assert.IsType<PaymentprocessorMoney>(instance);
        }

        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Fact]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }

        /// <summary>
        /// Test the property 'Micros'
        /// </summary>
        [Fact]
        public void MicrosTest()
        {
            // TODO unit test for the property 'Micros'
        }
    }
}
