/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorListAvailablePaymentMethodsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorListAvailablePaymentMethodsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorListAvailablePaymentMethodsResponse
        //private PaymentprocessorListAvailablePaymentMethodsResponse instance;

        public PaymentprocessorListAvailablePaymentMethodsResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorListAvailablePaymentMethodsResponse
            //instance = new PaymentprocessorListAvailablePaymentMethodsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorListAvailablePaymentMethodsResponse
        /// </summary>
        [Fact]
        public void PaymentprocessorListAvailablePaymentMethodsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorListAvailablePaymentMethodsResponse
            //Assert.IsType<PaymentprocessorListAvailablePaymentMethodsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Methods'
        /// </summary>
        [Fact]
        public void MethodsTest()
        {
            // TODO unit test for the property 'Methods'
        }
    }
}
