/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorFinalizePaymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorFinalizePaymentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorFinalizePaymentResponse
        //private PaymentprocessorFinalizePaymentResponse instance;

        public PaymentprocessorFinalizePaymentResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorFinalizePaymentResponse
            //instance = new PaymentprocessorFinalizePaymentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorFinalizePaymentResponse
        /// </summary>
        [Fact]
        public void PaymentprocessorFinalizePaymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorFinalizePaymentResponse
            //Assert.IsType<PaymentprocessorFinalizePaymentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Transaction'
        /// </summary>
        [Fact]
        public void TransactionTest()
        {
            // TODO unit test for the property 'Transaction'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
    }
}
