/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorInitPaymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorInitPaymentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorInitPaymentResponse
        //private PaymentprocessorInitPaymentResponse instance;

        public PaymentprocessorInitPaymentResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorInitPaymentResponse
            //instance = new PaymentprocessorInitPaymentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorInitPaymentResponse
        /// </summary>
        [Fact]
        public void PaymentprocessorInitPaymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorInitPaymentResponse
            //Assert.IsType<PaymentprocessorInitPaymentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
    }
}
