/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorGetPaymentMethodConfigurationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorGetPaymentMethodConfigurationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorGetPaymentMethodConfigurationResponse
        //private PaymentprocessorGetPaymentMethodConfigurationResponse instance;

        public PaymentprocessorGetPaymentMethodConfigurationResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorGetPaymentMethodConfigurationResponse
            //instance = new PaymentprocessorGetPaymentMethodConfigurationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorGetPaymentMethodConfigurationResponse
        /// </summary>
        [Fact]
        public void PaymentprocessorGetPaymentMethodConfigurationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorGetPaymentMethodConfigurationResponse
            //Assert.IsType<PaymentprocessorGetPaymentMethodConfigurationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VarConfiguration'
        /// </summary>
        [Fact]
        public void VarConfigurationTest()
        {
            // TODO unit test for the property 'VarConfiguration'
        }
    }
}
