/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorPaymentMethodRestriction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorPaymentMethodRestrictionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorPaymentMethodRestriction
        //private PaymentprocessorPaymentMethodRestriction instance;

        public PaymentprocessorPaymentMethodRestrictionTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorPaymentMethodRestriction
            //instance = new PaymentprocessorPaymentMethodRestriction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorPaymentMethodRestriction
        /// </summary>
        [Fact]
        public void PaymentprocessorPaymentMethodRestrictionInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorPaymentMethodRestriction
            //Assert.IsType<PaymentprocessorPaymentMethodRestriction>(instance);
        }

        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Fact]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }
    }
}
