/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorTransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorTransaction
        //private PaymentprocessorTransaction instance;

        public PaymentprocessorTransactionTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorTransaction
            //instance = new PaymentprocessorTransaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorTransaction
        /// </summary>
        [Fact]
        public void PaymentprocessorTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorTransaction
            //Assert.IsType<PaymentprocessorTransaction>(instance);
        }

        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }

        /// <summary>
        /// Test the property 'ChildTransactions'
        /// </summary>
        [Fact]
        public void ChildTransactionsTest()
        {
            // TODO unit test for the property 'ChildTransactions'
        }
    }
}
