/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorAvailabilityContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorAvailabilityContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorAvailabilityContext
        //private PaymentprocessorAvailabilityContext instance;

        public PaymentprocessorAvailabilityContextTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorAvailabilityContext
            //instance = new PaymentprocessorAvailabilityContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorAvailabilityContext
        /// </summary>
        [Fact]
        public void PaymentprocessorAvailabilityContextInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorAvailabilityContext
            //Assert.IsType<PaymentprocessorAvailabilityContext>(instance);
        }

        /// <summary>
        /// Test the property 'ShippingAddress'
        /// </summary>
        [Fact]
        public void ShippingAddressTest()
        {
            // TODO unit test for the property 'ShippingAddress'
        }

        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Fact]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }

        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Fact]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
    }
}
