/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorVoidPaymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorVoidPaymentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorVoidPaymentResponse
        //private PaymentprocessorVoidPaymentResponse instance;

        public PaymentprocessorVoidPaymentResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorVoidPaymentResponse
            //instance = new PaymentprocessorVoidPaymentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorVoidPaymentResponse
        /// </summary>
        [Fact]
        public void PaymentprocessorVoidPaymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorVoidPaymentResponse
            //Assert.IsType<PaymentprocessorVoidPaymentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Transaction'
        /// </summary>
        [Fact]
        public void TransactionTest()
        {
            // TODO unit test for the property 'Transaction'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
    }
}
