/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentMethodRestrictionConditionCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentMethodRestrictionConditionConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentMethodRestrictionConditionCondition
        //private PaymentMethodRestrictionConditionCondition instance;

        public PaymentMethodRestrictionConditionConditionTests()
        {
            // TODO uncomment below to create an instance of PaymentMethodRestrictionConditionCondition
            //instance = new PaymentMethodRestrictionConditionCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentMethodRestrictionConditionCondition
        /// </summary>
        [Fact]
        public void PaymentMethodRestrictionConditionConditionInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentMethodRestrictionConditionCondition
            //Assert.IsType<PaymentMethodRestrictionConditionCondition>(instance);
        }
    }
}
