/*
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using paymentprocessor.Model;
using paymentprocessor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace paymentprocessor.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentprocessorAvailabilityContextPostalAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentprocessorAvailabilityContextPostalAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentprocessorAvailabilityContextPostalAddress
        //private PaymentprocessorAvailabilityContextPostalAddress instance;

        public PaymentprocessorAvailabilityContextPostalAddressTests()
        {
            // TODO uncomment below to create an instance of PaymentprocessorAvailabilityContextPostalAddress
            //instance = new PaymentprocessorAvailabilityContextPostalAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentprocessorAvailabilityContextPostalAddress
        /// </summary>
        [Fact]
        public void PaymentprocessorAvailabilityContextPostalAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentprocessorAvailabilityContextPostalAddress
            //Assert.IsType<PaymentprocessorAvailabilityContextPostalAddress>(instance);
        }

        /// <summary>
        /// Test the property 'RegionCode'
        /// </summary>
        [Fact]
        public void RegionCodeTest()
        {
            // TODO unit test for the property 'RegionCode'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Fact]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }

        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Fact]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }

        /// <summary>
        /// Test the property 'AddressLines'
        /// </summary>
        [Fact]
        public void AddressLinesTest()
        {
            // TODO unit test for the property 'AddressLines'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
    }
}
